name: $(Build.BuildId)

trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
  branches:
    include:
      - master

stages:
  - stage: Build_platforms
    jobs:
      - template: .ci/build-platform.yml
        parameters:
          platform: Linux
          vmImage: ubuntu-16.04
          STAGING_DIRECTORY: /home/vsts/STAGING
          STAGING_DIRECTORY_UNIX: /home/vsts/STAGING
          ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source/i

      - template: .ci/build-platform.yml
        parameters:
          platform: macOS
          vmImage: macOS-latest
          STAGING_DIRECTORY: /Users/vsts/STAGING
          STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
          ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i

      - template: .ci/build-platform.yml
        parameters:
          platform: Windows
          vmImage: vs2017-win2016
          STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING
          STAGING_DIRECTORY_UNIX: /C/Users/VssAdministrator/STAGING
          ESY__CACHE_INSTALL_PATH: /C/Users/VssAdministrator/.esy/3_/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /C/Users/VssAdministrator/.esy/source/i

  - stage: Create_release
    dependsOn: [Build_platforms]
    jobs:
    - job: Release
      displayName: Release
      pool:
        vmImage: ubuntu-16.04
      steps:
        - template: .ci/cross-release.yml

  - stage: Test_releases
    dependsOn: [Create_release]
    jobs:
    - job: TestReleaseLinux
      displayName: Test Release Linux
      pool:
        vmImage: ubuntu-16.04
      steps:
        - template: .ci/test-release.yml

    - job: TestReleasOsX
      displayName: Test Release osX
      pool:
        vmImage: macOS-latest
      steps:
        - template: .ci/test-release.yml

    - job: TestReleaseWindows
      displayName: Test Release Windows
      pool:
        vmImage: vs2017-win2016
      steps:
        - template: .ci/test-release.yml
